CREATE TABLE `conditions` (
	`slug` text PRIMARY KEY NOT NULL,
	`key` text NOT NULL,
	`name` text NOT NULL,
	`desc` text NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX `conditions_key_unique` ON `conditions` (`key`);--> statement-breakpoint
CREATE TABLE `creature_action_attacks` (
	`slug` text PRIMARY KEY NOT NULL,
	`action_slug` text NOT NULL,
	`name` text NOT NULL,
	`attack_type` text,
	`to_hit_mod` integer,
	`reach` integer,
	`range` integer,
	`long_range` integer,
	`target_creature_only` integer DEFAULT false NOT NULL,
	`damage_die_count` integer,
	`damage_die_type` text,
	`damage_bonus` integer,
	`damage_type` text,
	`extra_damage_die_count` integer,
	`extra_damage_die_type` text,
	`extra_damage_bonus` integer,
	`extra_damage_type` text,
	FOREIGN KEY (`action_slug`) REFERENCES `creature_actions`(`slug`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `creature_actions` (
	`slug` text PRIMARY KEY NOT NULL,
	`creature_slug` text NOT NULL,
	`name` text NOT NULL,
	`desc` text NOT NULL,
	`action_type` text NOT NULL,
	`sort_order` integer DEFAULT 0 NOT NULL,
	`legendary_action_cost` integer,
	`uses_type` text,
	`uses_param` integer,
	FOREIGN KEY (`creature_slug`) REFERENCES `creatures`(`slug`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `creature_traits` (
	`slug` text PRIMARY KEY NOT NULL,
	`creature_slug` text NOT NULL,
	`name` text NOT NULL,
	`desc` text NOT NULL,
	`type` text,
	FOREIGN KEY (`creature_slug`) REFERENCES `creatures`(`slug`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `creatures` (
	`slug` text PRIMARY KEY NOT NULL,
	`document` text NOT NULL,
	`name` text NOT NULL,
	`size` text NOT NULL,
	`type` text NOT NULL,
	`category` text NOT NULL,
	`alignment` text NOT NULL,
	`challenge_rating` real NOT NULL,
	`armor_class` integer NOT NULL,
	`armor_detail` text,
	`hit_points` integer NOT NULL,
	`hit_dice` text NOT NULL,
	`initiative_bonus` integer,
	`ability_score_strength` integer NOT NULL,
	`ability_score_dexterity` integer NOT NULL,
	`ability_score_constitution` integer,
	`ability_score_intelligence` integer NOT NULL,
	`ability_score_wisdom` integer NOT NULL,
	`ability_score_charisma` integer NOT NULL,
	`saving_throw_strength` integer,
	`saving_throw_dexterity` integer,
	`saving_throw_constitution` integer,
	`saving_throw_intelligence` integer,
	`saving_throw_wisdom` integer,
	`saving_throw_charisma` integer,
	`skill_bonus_acrobatics` integer,
	`skill_bonus_animal_handling` integer,
	`skill_bonus_arcana` integer,
	`skill_bonus_athletics` integer,
	`skill_bonus_deception` integer,
	`skill_bonus_history` integer,
	`skill_bonus_insight` integer,
	`skill_bonus_intimidation` integer,
	`skill_bonus_investigation` integer,
	`skill_bonus_medicine` integer,
	`skill_bonus_nature` integer,
	`skill_bonus_perception` integer,
	`skill_bonus_performance` integer,
	`skill_bonus_persuasion` integer,
	`skill_bonus_religion` integer,
	`skill_bonus_sleight_of_hand` integer,
	`skill_bonus_stealth` integer,
	`skill_bonus_survival` integer,
	`walk` integer,
	`swim` integer,
	`fly` integer,
	`climb` integer,
	`burrow` integer,
	`hover` integer DEFAULT false NOT NULL,
	`darkvision_range` integer,
	`blindsight_range` integer,
	`tremorsense_range` integer,
	`truesight_range` integer,
	`telepathy_range` integer,
	`passive_perception` integer NOT NULL,
	`damage_immunities` text DEFAULT '[]' NOT NULL,
	`damage_immunities_display` text,
	`damage_resistances` text DEFAULT '[]' NOT NULL,
	`damage_resistances_display` text,
	`damage_vulnerabilities` text DEFAULT '[]' NOT NULL,
	`damage_vulnerabilities_display` text,
	`condition_immunities` text DEFAULT '[]' NOT NULL,
	`condition_immunities_display` text,
	`nonmagical_attack_immunity` integer DEFAULT false NOT NULL,
	`nonmagical_attack_resistance` integer DEFAULT false NOT NULL,
	`languages` text DEFAULT '[]' NOT NULL,
	`languages_desc` text
);
--> statement-breakpoint
CREATE TABLE `import_runs` (
	`id` text PRIMARY KEY NOT NULL,
	`git_ref` text NOT NULL,
	`started_at` integer NOT NULL,
	`finished_at` integer,
	`creature_count` integer DEFAULT 0 NOT NULL,
	`action_count` integer DEFAULT 0 NOT NULL,
	`attack_count` integer DEFAULT 0 NOT NULL,
	`trait_count` integer DEFAULT 0 NOT NULL,
	`condition_count` integer DEFAULT 0 NOT NULL,
	`error` text
);
